version: '2.2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_user
      MONGO_INITDB_ROOT_PASSWORD: my_password
      MONGO_DATA_DIR: /data/db
    restart: always
    volumes:
      - mongodb_data:/data/db
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_project_db

volumes:
  mongodb_data:
