# services:
#   mongodb:
#     image: 'mongo:latest'
#     environment:
#       - 'MONGO_INITDB_DATABASE=qrstaDB'
#       - 'MONGO_INITDB_ROOT_PASSWORD=qrsta-12-23-postgres'
#       - 'MONGO_INITDB_ROOT_USERNAME=madkour'
#     ports:
#       - '27017'
#   postgres:
#     image: 'postgres:latest'
#     environment:
#       - 'POSTGRES_USER=myuser'
#       - 'POSTGRES_DB=mydatabase'
#       - 'POSTGRES_PASSWORD=secret'
#     ports:
#       - '5432:5432'
version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27070:27017"
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my-project-db

  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
#  java-service:
#    build: .
#    links:
#      - redis-server
#      - mongodb
#      - postgres-db
#    ports:
#      - "8081:8081"