version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27070:27017"
    volumes:
      - dbdata6:/data/db
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
     
      POSTGRES_DB: my-project-db
volumes:
  dbdata6: